language: python
# Add or remove version for match with Travis support
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
os:
  - linux

matrix:
  fast_finish: true
  include:
    - env: ENV=lint
      python: 2.7
      before_script: TOX_ENV=lint

install:
  - pip install --upgrade "pip<8.0.0"
  - pip install "virtualenv<14.0.0"
  - pip install "tox>=2.3.0,<2.4"
  - TOX_ENV=py$TRAVIS_PYTHON_VERSION

script:
  - tox -e $TOX_ENV
